on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Tests this
    steps:
    # To use this repository's private action, you must check out the repository
    - name: Checkout
      uses: actions/checkout@v1
    - name: Runs tests
      id: tests
      uses: JJ/raku-container-action@master
